# Generated by Django 3.0.5 on 2020-09-14 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Postagens',
        ),
    ]
